In [ ]:
import numpy as np 
import pandas as pd 
import os
import cv2
​
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layer

In [ ]:
batch_size = 40
img_height = 256
img_width = 256

In [ ]:
## loading training data
training_ds = tf.keras.preprocessing.image_dataset_from_directory(
    '/kaggle/input/yawn-eye-dataset-new/dataset_new/train',
    validation_split=0.2,
    subset= "training",
    seed=42,
    image_size= (img_height, img_width),
    batch_size=batch_size )

Found 2467 files belonging to 4 classes.
Using 1974 files for training.

In [ ]:
## loading testing data
testing_ds = tf.keras.preprocessing.image_dataset_from_directory(
'/kaggle/input/yawn-eye-dataset-new/dataset_new/test',
    validation_split=0.2,
    subset= "validation",
    seed=42,
    image_size= (img_height, img_width),
    batch_size=batch_size )


Found 433 files belonging to 4 classes.
Using 86 files for validation.

In [ ]:
class_names = training_ds.class_names
print(class_names)

['Closed', 'Open', 'no_yawn', 'yawn']

In [ ]:
for images, labels in training_ds.take(1):
  for i in range(2):
    print(images)

tf.Tensor(
[[[[3.52910156e+01 2.32910156e+01 7.29101562e+00]
   [3.68730469e+01 2.48730469e+01 8.87304688e+00]
   [3.89101562e+01 2.64550781e+01 1.00000000e+01]
   ...
   [1.78544922e+02 1.41544922e+02 1.23544922e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]
   [1.79648056e+02 1.42648056e+02 1.24648056e+02]]

  [[3.52910156e+01 2.32910156e+01 7.29101562e+00]
   [3.68730469e+01 2.50981293e+01 8.64796448e+00]
   [3.90274811e+01 2.67128906e+01 9.97683716e+00]
   ...
   [1.78404434e+02 1.41404434e+02 1.23404434e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]]

  [[3.52910156e+01 2.32910156e+01 7.29101562e+00]
   [3.72481842e+01 2.61212311e+01 8.37513733e+00]
   [3.95993805e+01 2.76892242e+01 1.01443024e+01]
   ...
   [1.78000000e+02 1.41000000e+02 1.23000000e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]]

  ...

  [[1.09429688e+02 7.34296875e+01 4.14296875e+01]
   [1.09429688e+02 7.34296875e+01 4.14296875e+01]
   [1.08740463e+02 7.31955414e+01 4.21056976e+01]
   ...
   [1.58000000e+02 1.04000000e+02 7.80000000e+01]
   [1.59126953e+02 1.05126953e+02 7.91269531e+01]
   [1.60708984e+02 1.06708984e+02 8.07089844e+01]]

  [[1.09000000e+02 7.30000000e+01 4.10000000e+01]
   [1.09000000e+02 7.30000000e+01 4.10000000e+01]
   [1.08544922e+02 7.30000000e+01 4.19101562e+01]
   ...
   [1.58000000e+02 1.04000000e+02 7.80000000e+01]
   [1.59126953e+02 1.05126953e+02 7.91269531e+01]
   [1.60708984e+02 1.06708984e+02 8.07089844e+01]]

  [[1.09000000e+02 7.30000000e+01 4.10000000e+01]
   [1.09000000e+02 7.30000000e+01 4.10000000e+01]
   [1.08544922e+02 7.30000000e+01 4.19101562e+01]
   ...
   [1.58000000e+02 1.04000000e+02 7.80000000e+01]
   [1.59126953e+02 1.05126953e+02 7.91269531e+01]
   [1.60708984e+02 1.06708984e+02 8.07089844e+01]]]


 [[[5.11875000e+01 4.91875000e+01 3.41875000e+01]
   [5.08750000e+01 5.05625000e+01 3.50000000e+01]
   [4.81250000e+01 4.91250000e+01 3.31250000e+01]
   ...
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]]

  [[5.11875000e+01 4.91875000e+01 3.41875000e+01]
   [5.08750000e+01 5.05625000e+01 3.50000000e+01]
   [4.81250000e+01 4.91250000e+01 3.31250000e+01]
   ...
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]]

  [[5.11875000e+01 4.91875000e+01 3.41875000e+01]
   [5.06333008e+01 5.03208008e+01 3.47583008e+01]
   [4.80981445e+01 4.90981445e+01 3.30981445e+01]
   ...
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]]

  ...

  [[2.20187500e+02 1.76187500e+02 1.51187500e+02]
   [2.21000000e+02 1.77000000e+02 1.52000000e+02]
   [2.20062500e+02 1.76062500e+02 1.51062500e+02]
   ...
   [2.33062500e+02 1.87062500e+02 1.71062500e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]]

  [[2.20187500e+02 1.76187500e+02 1.51187500e+02]
   [2.21000000e+02 1.77000000e+02 1.52000000e+02]
   [2.20062500e+02 1.76062500e+02 1.51062500e+02]
   ...
   [2.33062500e+02 1.87062500e+02 1.71062500e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]]

  [[2.20187500e+02 1.76187500e+02 1.51187500e+02]
   [2.21000000e+02 1.77000000e+02 1.52000000e+02]
   [2.20062500e+02 1.76062500e+02 1.51062500e+02]
   ...
   [2.33062500e+02 1.87062500e+02 1.71062500e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]
   [2.34742676e+02 1.88742676e+02 1.72742676e+02]]]


 [[[2.10000000e+01 2.40000000e+01 1.70000000e+01]
   [2.10000000e+01 2.40000000e+01 1.70000000e+01]
   [2.10000000e+01 2.40000000e+01 1.70000000e+01]
   ...
   [1.91406250e+02 2.33078125e+02 2.46531250e+02]
   [1.92703125e+02 2.35546875e+02 2.48906250e+02]
   [1.95953125e+02 2.39078125e+02 2.51203125e+02]]

  [[2.10000000e+01 2.40000000e+01 1.70000000e+01]
   [2.10000000e+01 2.40000000e+01 1.70000000e+01]
   [2.10000000e+01 2.40000000e+01 1.70000000e+01]
   ...
   [2.04296875e+02 2.43015625e+02 2.53218750e+02]
   [2.06078125e+02 2.45140625e+02 2.54828125e+02]
   [2.07109375e+02 2.46171875e+02 2.55000000e+02]]

  [[2.20000000e+01 2.30000000e+01 1.70000000e+01]
   [2.20000000e+01 2.30000000e+01 1.70000000e+01]
   [2.20000000e+01 2.30000000e+01 1.70000000e+01]
   ...
   [2.14187500e+02 2.48000000e+02 2.54718750e+02]
   [2.13187500e+02 2.47000000e+02 2.54718750e+02]
   [2.12437500e+02 2.46250000e+02 2.54671875e+02]]

  ...

  [[6.43750000e+00 8.43750000e+00 7.43750000e+00]
   [2.89062500e+00 4.89062500e+00 3.89062500e+00]
   [4.68750000e-02 1.43750000e+00 4.37500000e-01]
   ...
   [5.33750000e+01 4.88750000e+01 3.63125000e+01]
   [8.05468750e+01 8.20156250e+01 7.38750000e+01]
   [9.13593750e+01 9.62812500e+01 9.15312500e+01]]

  [[4.70312500e+00 6.70312500e+00 5.70312500e+00]
   [2.12500000e+00 4.12500000e+00 1.29687500e+00]
   [7.81250000e-02 1.15625000e+00 0.00000000e+00]
   ...
   [5.97656250e+01 6.18750000e+01 5.83593750e+01]
   [4.65625000e+01 5.40312500e+01 5.27343750e+01]
   [5.45312500e+01 6.35312500e+01 6.19062500e+01]]

  [[4.37500000e-01 2.43750000e+00 0.00000000e+00]
   [0.00000000e+00 1.75000000e+00 0.00000000e+00]
   [0.00000000e+00 1.00000000e+00 0.00000000e+00]
   ...
   [2.92343750e+01 3.40156250e+01 3.60312500e+01]
   [5.65625000e+01 6.11406250e+01 6.41406250e+01]
   [6.87031250e+01 7.35781250e+01 7.41406250e+01]]]


 ...


 [[[1.24562500e+02 1.26562500e+02 1.15562500e+02]
   [1.24312500e+02 1.26562500e+02 1.16062500e+02]
   [1.23562500e+02 1.26562500e+02 1.17562500e+02]
   ...
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.57500000e+01 9.60000000e+01 8.80000000e+01]
   [9.60000000e+01 9.60000000e+01 8.80000000e+01]]

  [[1.24312500e+02 1.26312500e+02 1.15312500e+02]
   [1.24062500e+02 1.26312500e+02 1.15312500e+02]
   [1.23312500e+02 1.26312500e+02 1.16812500e+02]
   ...
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.60000000e+01 9.60000000e+01 8.80000000e+01]]

  [[1.23812500e+02 1.25812500e+02 1.14812500e+02]
   [1.23562500e+02 1.25812500e+02 1.14812500e+02]
   [1.22812500e+02 1.25812500e+02 1.16312500e+02]
   ...
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]]

  ...

  [[3.24375000e+01 3.44375000e+01 3.34375000e+01]
   [3.15781250e+01 3.35781250e+01 3.05781250e+01]
   [3.10468750e+01 3.30468750e+01 3.00468750e+01]
   ...
   [4.97500000e+01 5.47500000e+01 6.07500000e+01]
   [5.04531250e+01 5.39531250e+01 5.92031250e+01]
   [5.15625000e+01 5.45625000e+01 5.95625000e+01]]

  [[3.13281250e+01 3.33281250e+01 3.03281250e+01]
   [3.10000000e+01 3.30000000e+01 2.95000000e+01]
   [3.04843750e+01 3.24843750e+01 2.89843750e+01]
   ...
   [4.63125000e+01 5.13125000e+01 5.73125000e+01]
   [4.66875000e+01 5.01875000e+01 5.69375000e+01]
   [4.67656250e+01 4.97656250e+01 5.47656250e+01]]

  [[3.12500000e+01 3.32500000e+01 3.02500000e+01]
   [3.10000000e+01 3.30000000e+01 2.80000000e+01]
   [3.01093750e+01 3.21093750e+01 2.86093750e+01]
   ...
   [4.38593750e+01 4.81093750e+01 5.63593750e+01]
   [4.24375000e+01 4.59375000e+01 5.26875000e+01]
   [4.24375000e+01 4.54375000e+01 5.04375000e+01]]]


 [[[1.95781250e+02 2.01781250e+02 1.99781250e+02]
   [1.89046875e+02 1.95046875e+02 1.93046875e+02]
   [1.89609375e+02 1.95609375e+02 1.93609375e+02]
   ...
   [1.44843750e+02 1.28375000e+02 1.33390625e+02]
   [1.39640625e+02 1.20484375e+02 1.31687500e+02]
   [1.36937500e+02 1.19500000e+02 1.36625000e+02]]

  [[1.84968750e+02 1.93968750e+02 1.90968750e+02]
   [1.90781250e+02 1.99781250e+02 1.96781250e+02]
   [1.89718750e+02 1.98718750e+02 1.95718750e+02]
   ...
   [1.91218750e+02 1.70671875e+02 1.70671875e+02]
   [1.77359375e+02 1.55187500e+02 1.60593750e+02]
   [1.79296875e+02 1.56046875e+02 1.67796875e+02]]

  [[1.85468750e+02 1.96468750e+02 1.92468750e+02]
   [1.93781250e+02 2.04781250e+02 2.00781250e+02]
   [1.92218750e+02 2.03218750e+02 1.99218750e+02]
   ...
   [2.15859375e+02 1.88703125e+02 1.80953125e+02]
   [2.34906250e+02 2.06671875e+02 2.02578125e+02]
   [2.34015625e+02 2.03015625e+02 2.04875000e+02]]

  ...

  [[9.31406250e+01 9.41406250e+01 8.81406250e+01]
   [8.69375000e+01 8.79375000e+01 8.19375000e+01]
   [7.52343750e+01 7.62343750e+01 7.02343750e+01]
   ...
   [2.53984375e+02 2.35093750e+02 2.29531250e+02]
   [2.51484375e+02 2.27281250e+02 2.23421875e+02]
   [2.13281250e+02 1.84906250e+02 1.82093750e+02]]

  [[9.13125000e+01 9.23125000e+01 8.63125000e+01]
   [8.55781250e+01 8.65781250e+01 8.05781250e+01]
   [7.33125000e+01 7.43125000e+01 6.83125000e+01]
   ...
   [2.54609375e+02 2.38015625e+02 2.31500000e+02]
   [2.50250000e+02 2.28890625e+02 2.23953125e+02]
   [2.52656250e+02 2.28859375e+02 2.24687500e+02]]

  [[9.00000000e+01 9.10000000e+01 8.50000000e+01]
   [8.55000000e+01 8.65000000e+01 8.05000000e+01]
   [7.20000000e+01 7.30000000e+01 6.70000000e+01]
   ...
   [2.55000000e+02 2.40312500e+02 2.33312500e+02]
   [2.54671875e+02 2.39015625e+02 2.32875000e+02]
   [2.49531250e+02 2.33109375e+02 2.27437500e+02]]]


 [[[2.36750000e+02 2.36750000e+02 2.36750000e+02]
   [2.36750000e+02 2.36750000e+02 2.36750000e+02]
   [2.36421875e+02 2.36421875e+02 2.36421875e+02]
   ...
   [1.51437500e+02 1.48437500e+02 1.41437500e+02]
   [1.52437500e+02 1.49437500e+02 1.42437500e+02]
   [1.51687500e+02 1.48687500e+02 1.41687500e+02]]

  [[2.41000000e+02 2.41000000e+02 2.41000000e+02]
   [2.41000000e+02 2.41000000e+02 2.41000000e+02]
   [2.41000000e+02 2.41000000e+02 2.41000000e+02]
   ...
   [1.53546875e+02 1.50546875e+02 1.43546875e+02]
   [1.54140625e+02 1.51140625e+02 1.44140625e+02]
   [1.53390625e+02 1.50390625e+02 1.43390625e+02]]

  [[2.41375000e+02 2.41375000e+02 2.41375000e+02]
   [2.40375000e+02 2.40375000e+02 2.40375000e+02]
   [2.41171875e+02 2.41171875e+02 2.41171875e+02]
   ...
   [1.55937500e+02 1.52937500e+02 1.45937500e+02]
   [1.56000000e+02 1.53000000e+02 1.46000000e+02]
   [1.55390625e+02 1.52390625e+02 1.45390625e+02]]

  ...

  [[1.69609375e+02 1.76609375e+02 1.92609375e+02]
   [1.78093750e+02 1.84593750e+02 2.01343750e+02]
   [1.75015625e+02 1.80015625e+02 1.99015625e+02]
   ...
   [9.38281250e+01 9.58281250e+01 1.16828125e+02]
   [9.20781250e+01 9.40781250e+01 1.15078125e+02]
   [8.90000000e+01 9.10000000e+01 1.12000000e+02]]

  [[1.77093750e+02 1.84093750e+02 2.00093750e+02]
   [1.74031250e+02 1.80531250e+02 1.97281250e+02]
   [1.77921875e+02 1.82921875e+02 2.01921875e+02]
   ...
   [9.04218750e+01 9.34218750e+01 1.12421875e+02]
   [8.89531250e+01 9.19531250e+01 1.10953125e+02]
   [8.74843750e+01 9.04843750e+01 1.09484375e+02]]

  [[1.72218750e+02 1.79218750e+02 1.95218750e+02]
   [1.75375000e+02 1.81875000e+02 1.98625000e+02]
   [1.79078125e+02 1.84078125e+02 2.03078125e+02]
   ...
   [8.43125000e+01 8.73125000e+01 1.06312500e+02]
   [8.43125000e+01 8.73125000e+01 1.06312500e+02]
   [8.49843750e+01 8.79843750e+01 1.06984375e+02]]]], shape=(40, 256, 256, 3), dtype=float32)
tf.Tensor(
[[[[3.52910156e+01 2.32910156e+01 7.29101562e+00]
   [3.68730469e+01 2.48730469e+01 8.87304688e+00]
   [3.89101562e+01 2.64550781e+01 1.00000000e+01]
   ...
   [1.78544922e+02 1.41544922e+02 1.23544922e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]
   [1.79648056e+02 1.42648056e+02 1.24648056e+02]]

  [[3.52910156e+01 2.32910156e+01 7.29101562e+00]
   [3.68730469e+01 2.50981293e+01 8.64796448e+00]
   [3.90274811e+01 2.67128906e+01 9.97683716e+00]
   ...
   [1.78404434e+02 1.41404434e+02 1.23404434e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]]

  [[3.52910156e+01 2.32910156e+01 7.29101562e+00]
   [3.72481842e+01 2.61212311e+01 8.37513733e+00]
   [3.95993805e+01 2.76892242e+01 1.01443024e+01]
   ...
   [1.78000000e+02 1.41000000e+02 1.23000000e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]
   [1.79000000e+02 1.42000000e+02 1.24000000e+02]]

  ...

  [[1.09429688e+02 7.34296875e+01 4.14296875e+01]
   [1.09429688e+02 7.34296875e+01 4.14296875e+01]
   [1.08740463e+02 7.31955414e+01 4.21056976e+01]
   ...
   [1.58000000e+02 1.04000000e+02 7.80000000e+01]
   [1.59126953e+02 1.05126953e+02 7.91269531e+01]
   [1.60708984e+02 1.06708984e+02 8.07089844e+01]]

  [[1.09000000e+02 7.30000000e+01 4.10000000e+01]
   [1.09000000e+02 7.30000000e+01 4.10000000e+01]
   [1.08544922e+02 7.30000000e+01 4.19101562e+01]
   ...
   [1.58000000e+02 1.04000000e+02 7.80000000e+01]
   [1.59126953e+02 1.05126953e+02 7.91269531e+01]
   [1.60708984e+02 1.06708984e+02 8.07089844e+01]]

  [[1.09000000e+02 7.30000000e+01 4.10000000e+01]
   [1.09000000e+02 7.30000000e+01 4.10000000e+01]
   [1.08544922e+02 7.30000000e+01 4.19101562e+01]
   ...
   [1.58000000e+02 1.04000000e+02 7.80000000e+01]
   [1.59126953e+02 1.05126953e+02 7.91269531e+01]
   [1.60708984e+02 1.06708984e+02 8.07089844e+01]]]


 [[[5.11875000e+01 4.91875000e+01 3.41875000e+01]
   [5.08750000e+01 5.05625000e+01 3.50000000e+01]
   [4.81250000e+01 4.91250000e+01 3.31250000e+01]
   ...
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]]

  [[5.11875000e+01 4.91875000e+01 3.41875000e+01]
   [5.08750000e+01 5.05625000e+01 3.50000000e+01]
   [4.81250000e+01 4.91250000e+01 3.31250000e+01]
   ...
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]]

  [[5.11875000e+01 4.91875000e+01 3.41875000e+01]
   [5.06333008e+01 5.03208008e+01 3.47583008e+01]
   [4.80981445e+01 4.90981445e+01 3.30981445e+01]
   ...
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]
   [2.36000000e+02 1.83000000e+02 1.67000000e+02]]

  ...

  [[2.20187500e+02 1.76187500e+02 1.51187500e+02]
   [2.21000000e+02 1.77000000e+02 1.52000000e+02]
   [2.20062500e+02 1.76062500e+02 1.51062500e+02]
   ...
   [2.33062500e+02 1.87062500e+02 1.71062500e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]]

  [[2.20187500e+02 1.76187500e+02 1.51187500e+02]
   [2.21000000e+02 1.77000000e+02 1.52000000e+02]
   [2.20062500e+02 1.76062500e+02 1.51062500e+02]
   ...
   [2.33062500e+02 1.87062500e+02 1.71062500e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]]

  [[2.20187500e+02 1.76187500e+02 1.51187500e+02]
   [2.21000000e+02 1.77000000e+02 1.52000000e+02]
   [2.20062500e+02 1.76062500e+02 1.51062500e+02]
   ...
   [2.33062500e+02 1.87062500e+02 1.71062500e+02]
   [2.34000000e+02 1.88000000e+02 1.72000000e+02]
   [2.34742676e+02 1.88742676e+02 1.72742676e+02]]]


 [[[2.10000000e+01 2.40000000e+01 1.70000000e+01]
   [2.10000000e+01 2.40000000e+01 1.70000000e+01]
   [2.10000000e+01 2.40000000e+01 1.70000000e+01]
   ...
   [1.91406250e+02 2.33078125e+02 2.46531250e+02]
   [1.92703125e+02 2.35546875e+02 2.48906250e+02]
   [1.95953125e+02 2.39078125e+02 2.51203125e+02]]

  [[2.10000000e+01 2.40000000e+01 1.70000000e+01]
   [2.10000000e+01 2.40000000e+01 1.70000000e+01]
   [2.10000000e+01 2.40000000e+01 1.70000000e+01]
   ...
   [2.04296875e+02 2.43015625e+02 2.53218750e+02]
   [2.06078125e+02 2.45140625e+02 2.54828125e+02]
   [2.07109375e+02 2.46171875e+02 2.55000000e+02]]

  [[2.20000000e+01 2.30000000e+01 1.70000000e+01]
   [2.20000000e+01 2.30000000e+01 1.70000000e+01]
   [2.20000000e+01 2.30000000e+01 1.70000000e+01]
   ...
   [2.14187500e+02 2.48000000e+02 2.54718750e+02]
   [2.13187500e+02 2.47000000e+02 2.54718750e+02]
   [2.12437500e+02 2.46250000e+02 2.54671875e+02]]

  ...

  [[6.43750000e+00 8.43750000e+00 7.43750000e+00]
   [2.89062500e+00 4.89062500e+00 3.89062500e+00]
   [4.68750000e-02 1.43750000e+00 4.37500000e-01]
   ...
   [5.33750000e+01 4.88750000e+01 3.63125000e+01]
   [8.05468750e+01 8.20156250e+01 7.38750000e+01]
   [9.13593750e+01 9.62812500e+01 9.15312500e+01]]

  [[4.70312500e+00 6.70312500e+00 5.70312500e+00]
   [2.12500000e+00 4.12500000e+00 1.29687500e+00]
   [7.81250000e-02 1.15625000e+00 0.00000000e+00]
   ...
   [5.97656250e+01 6.18750000e+01 5.83593750e+01]
   [4.65625000e+01 5.40312500e+01 5.27343750e+01]
   [5.45312500e+01 6.35312500e+01 6.19062500e+01]]

  [[4.37500000e-01 2.43750000e+00 0.00000000e+00]
   [0.00000000e+00 1.75000000e+00 0.00000000e+00]
   [0.00000000e+00 1.00000000e+00 0.00000000e+00]
   ...
   [2.92343750e+01 3.40156250e+01 3.60312500e+01]
   [5.65625000e+01 6.11406250e+01 6.41406250e+01]
   [6.87031250e+01 7.35781250e+01 7.41406250e+01]]]


 ...


 [[[1.24562500e+02 1.26562500e+02 1.15562500e+02]
   [1.24312500e+02 1.26562500e+02 1.16062500e+02]
   [1.23562500e+02 1.26562500e+02 1.17562500e+02]
   ...
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.57500000e+01 9.60000000e+01 8.80000000e+01]
   [9.60000000e+01 9.60000000e+01 8.80000000e+01]]

  [[1.24312500e+02 1.26312500e+02 1.15312500e+02]
   [1.24062500e+02 1.26312500e+02 1.15312500e+02]
   [1.23312500e+02 1.26312500e+02 1.16812500e+02]
   ...
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.60000000e+01 9.60000000e+01 8.80000000e+01]]

  [[1.23812500e+02 1.25812500e+02 1.14812500e+02]
   [1.23562500e+02 1.25812500e+02 1.14812500e+02]
   [1.22812500e+02 1.25812500e+02 1.16312500e+02]
   ...
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]
   [9.50000000e+01 9.60000000e+01 8.80000000e+01]]

  ...

  [[3.24375000e+01 3.44375000e+01 3.34375000e+01]
   [3.15781250e+01 3.35781250e+01 3.05781250e+01]
   [3.10468750e+01 3.30468750e+01 3.00468750e+01]
   ...
   [4.97500000e+01 5.47500000e+01 6.07500000e+01]
   [5.04531250e+01 5.39531250e+01 5.92031250e+01]
   [5.15625000e+01 5.45625000e+01 5.95625000e+01]]

  [[3.13281250e+01 3.33281250e+01 3.03281250e+01]
   [3.10000000e+01 3.30000000e+01 2.95000000e+01]
   [3.04843750e+01 3.24843750e+01 2.89843750e+01]
   ...
   [4.63125000e+01 5.13125000e+01 5.73125000e+01]
   [4.66875000e+01 5.01875000e+01 5.69375000e+01]
   [4.67656250e+01 4.97656250e+01 5.47656250e+01]]

  [[3.12500000e+01 3.32500000e+01 3.02500000e+01]
   [3.10000000e+01 3.30000000e+01 2.80000000e+01]
   [3.01093750e+01 3.21093750e+01 2.86093750e+01]
   ...
   [4.38593750e+01 4.81093750e+01 5.63593750e+01]
   [4.24375000e+01 4.59375000e+01 5.26875000e+01]
   [4.24375000e+01 4.54375000e+01 5.04375000e+01]]]


 [[[1.95781250e+02 2.01781250e+02 1.99781250e+02]
   [1.89046875e+02 1.95046875e+02 1.93046875e+02]
   [1.89609375e+02 1.95609375e+02 1.93609375e+02]
   ...
   [1.44843750e+02 1.28375000e+02 1.33390625e+02]
   [1.39640625e+02 1.20484375e+02 1.31687500e+02]
   [1.36937500e+02 1.19500000e+02 1.36625000e+02]]

  [[1.84968750e+02 1.93968750e+02 1.90968750e+02]
   [1.90781250e+02 1.99781250e+02 1.96781250e+02]
   [1.89718750e+02 1.98718750e+02 1.95718750e+02]
   ...
   [1.91218750e+02 1.70671875e+02 1.70671875e+02]
   [1.77359375e+02 1.55187500e+02 1.60593750e+02]
   [1.79296875e+02 1.56046875e+02 1.67796875e+02]]

  [[1.85468750e+02 1.96468750e+02 1.92468750e+02]
   [1.93781250e+02 2.04781250e+02 2.00781250e+02]
   [1.92218750e+02 2.03218750e+02 1.99218750e+02]
   ...
   [2.15859375e+02 1.88703125e+02 1.80953125e+02]
   [2.34906250e+02 2.06671875e+02 2.02578125e+02]
   [2.34015625e+02 2.03015625e+02 2.04875000e+02]]

  ...

  [[9.31406250e+01 9.41406250e+01 8.81406250e+01]
   [8.69375000e+01 8.79375000e+01 8.19375000e+01]
   [7.52343750e+01 7.62343750e+01 7.02343750e+01]
   ...
   [2.53984375e+02 2.35093750e+02 2.29531250e+02]
   [2.51484375e+02 2.27281250e+02 2.23421875e+02]
   [2.13281250e+02 1.84906250e+02 1.82093750e+02]]

  [[9.13125000e+01 9.23125000e+01 8.63125000e+01]
   [8.55781250e+01 8.65781250e+01 8.05781250e+01]
   [7.33125000e+01 7.43125000e+01 6.83125000e+01]
   ...
   [2.54609375e+02 2.38015625e+02 2.31500000e+02]
   [2.50250000e+02 2.28890625e+02 2.23953125e+02]
   [2.52656250e+02 2.28859375e+02 2.24687500e+02]]

  [[9.00000000e+01 9.10000000e+01 8.50000000e+01]
   [8.55000000e+01 8.65000000e+01 8.05000000e+01]
   [7.20000000e+01 7.30000000e+01 6.70000000e+01]
   ...
   [2.55000000e+02 2.40312500e+02 2.33312500e+02]
   [2.54671875e+02 2.39015625e+02 2.32875000e+02]
   [2.49531250e+02 2.33109375e+02 2.27437500e+02]]]


 [[[2.36750000e+02 2.36750000e+02 2.36750000e+02]
   [2.36750000e+02 2.36750000e+02 2.36750000e+02]
   [2.36421875e+02 2.36421875e+02 2.36421875e+02]
   ...
   [1.51437500e+02 1.48437500e+02 1.41437500e+02]
   [1.52437500e+02 1.49437500e+02 1.42437500e+02]
   [1.51687500e+02 1.48687500e+02 1.41687500e+02]]

  [[2.41000000e+02 2.41000000e+02 2.41000000e+02]
   [2.41000000e+02 2.41000000e+02 2.41000000e+02]
   [2.41000000e+02 2.41000000e+02 2.41000000e+02]
   ...
   [1.53546875e+02 1.50546875e+02 1.43546875e+02]
   [1.54140625e+02 1.51140625e+02 1.44140625e+02]
   [1.53390625e+02 1.50390625e+02 1.43390625e+02]]

  [[2.41375000e+02 2.41375000e+02 2.41375000e+02]
   [2.40375000e+02 2.40375000e+02 2.40375000e+02]
   [2.41171875e+02 2.41171875e+02 2.41171875e+02]
   ...
   [1.55937500e+02 1.52937500e+02 1.45937500e+02]
   [1.56000000e+02 1.53000000e+02 1.46000000e+02]
   [1.55390625e+02 1.52390625e+02 1.45390625e+02]]

  ...

  [[1.69609375e+02 1.76609375e+02 1.92609375e+02]
   [1.78093750e+02 1.84593750e+02 2.01343750e+02]
   [1.75015625e+02 1.80015625e+02 1.99015625e+02]
   ...
   [9.38281250e+01 9.58281250e+01 1.16828125e+02]
   [9.20781250e+01 9.40781250e+01 1.15078125e+02]
   [8.90000000e+01 9.10000000e+01 1.12000000e+02]]

  [[1.77093750e+02 1.84093750e+02 2.00093750e+02]
   [1.74031250e+02 1.80531250e+02 1.97281250e+02]
   [1.77921875e+02 1.82921875e+02 2.01921875e+02]
   ...
   [9.04218750e+01 9.34218750e+01 1.12421875e+02]
   [8.89531250e+01 9.19531250e+01 1.10953125e+02]
   [8.74843750e+01 9.04843750e+01 1.09484375e+02]]

  [[1.72218750e+02 1.79218750e+02 1.95218750e+02]
   [1.75375000e+02 1.81875000e+02 1.98625000e+02]
   [1.79078125e+02 1.84078125e+02 2.03078125e+02]
   ...
   [8.43125000e+01 8.73125000e+01 1.06312500e+02]
   [8.43125000e+01 8.73125000e+01 1.06312500e+02]
   [8.49843750e+01 8.79843750e+01 1.06984375e+02]]]], shape=(40, 256, 256, 3), dtype=float32)

In [ ]:
plt.figure(figsize=(10, 10))
for images, labels in training_ds.take(1):
  for i in range(12):
    ax = plt.subplot(3,4 , i + 1)
    plt.imshow(images[i].numpy().astype("uint8"))
    plt.title(class_names[labels[i]])
    plt.grid(True)

In [ ]:
## Configuring dataset for performance
AUTOTUNE = tf.data.experimental.AUTOTUNE
training_ds = training_ds.cache().prefetch(buffer_size=AUTOTUNE)
testing_ds = testing_ds.cache().prefetch(buffer_size=AUTOTUNE)

In [ ]:
## lets define our CNN
MyCnn = tf.keras.models.Sequential([
  layers.experimental.preprocessing.Rescaling(1./255),
  layers.Conv2D(32, 3, activation='relu'),
  layers.MaxPooling2D(),
  layers.Conv2D(64, 3, activation='relu'),
  layers.MaxPooling2D(),
  layers.Conv2D(128, 3, activation='relu'),
  layers.MaxPooling2D(),

  layers.GlobalAveragePooling2D(),
  layers.Dense(256, activation='relu'),
  layers.Dense(len(class_names), activation= 'softmax')
])

In [ ]:
MyCnn.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
## lets train our CNN
retVal = MyCnn.fit(training_ds, validation_data= testing_ds, epochs = 10)

Epoch 1/10
62/62 [==============================] - 42s 557ms/step - loss: 1.1907 - accuracy: 0.3541 - val_loss: 0.8142 - val_accuracy: 0.4804
Epoch 2/10
62/62 [==============================] - 15s 240ms/step - loss: 0.7675 - accuracy: 0.5416 - val_loss: 0.7053 - val_accuracy: 0.6028
Epoch 3/10
62/62 [==============================] - 15s 240ms/step - loss: 0.7091 - accuracy: 0.5648 - val_loss: 0.6942 - val_accuracy: 0.5958
Epoch 4/10
62/62 [==============================] - 15s 241ms/step - loss: 0.6865 - accuracy: 0.5776 - val_loss: 0.6846 - val_accuracy: 0.6166
Epoch 5/10
62/62 [==============================] - 15s 240ms/step - loss: 0.6798 - accuracy: 0.5812 - val_loss: 0.6758 - val_accuracy: 0.6282
Epoch 6/10
62/62 [==============================] - 15s 240ms/step - loss: 0.6705 - accuracy: 0.5954 - val_loss: 0.6541 - val_accuracy: 0.6628
Epoch 7/10
62/62 [==============================] - 15s 240ms/step - loss: 0.6598 - accuracy: 0.6241 - val_loss: 0.6567 - val_accuracy: 0.6513
Epoch 8/10
62/62 [==============================] - 15s 241ms/step - loss: 0.6496 - accuracy: 0.6286 - val_loss: 0.6354 - val_accuracy: 0.6397
Epoch 9/10
62/62 [==============================] - 15s 240ms/step - loss: 0.6382 - accuracy: 0.6416 - val_loss: 0.6105 - val_accuracy: 0.6836
Epoch 10/10
62/62 [==============================] - 15s 241ms/step - loss: 0.6241 - accuracy: 0.6408 - val_loss: 0.6092 - val_accuracy: 0.6490

In [ ]:
plt.plot(retVal.history['loss'], label = 'training loss')
plt.plot(retVal.history['accuracy'], label = 'training accuracy')
plt.grid(True)
plt.legend()

In [ ]:
# saving model
MyCnn.save('drowsiness-stage1.h5')

In [ ]:
plt.figure(figsize=(20, 20))
for images, labels in testing_ds.take(2):
    predictions = MyCnn.predict(images)
    predlabel = []
    
    for mem in predictions:
        predlabel.append(class_names[np.argmax(mem)])
    
    for i in range(40):
        ax = plt.subplot(10, 4, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title('Predicted label:'+ predlabel[i])
        plt.axis('off')
        plt.grid(True)